title: Tim Bodeit
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Tim, a Developer from Munich, Germany
baseurl: "timbodeit.de" # the subpath of your site, e.g. /blog
url: "http://timbodeit.github.io" # the base hostname & protocol for your site
twitter_username: timbodeit
github_username:  timbodeit

# Build settings
markdown: kramdown
